# Christopher Gray - 11/11/2025
#
#   Cloudflare Family Sheild, OpenDNS Family - (Servers dont need to access porn! HA) - 208.67.222.123,1.1.1.3,9.9.9.9,2606:4700:4700::1113,2620:119:35::123,2620:fe::fe
#     Both IPv4 and IPv6
#
#  List of Non-Security Focused DNS Providers:
#       208.67.222.222,1.1.1.1,8.8.8.8,2001:4860:4860::8888,2620:0:ccc::2,2606:4700:4700::1111
#
#  Install:
#     wget https://raw.githubusercontent.com/c2theg/srvBuilds/master/configs/netplan-vlans-24_04.yaml && mv 01-netcfg.yaml /etc/netplan/netplan-vlans-24_04.yaml
#     cd /etc/netplan/
#
# -------------------------------------------------------
# Source: https://netplan.io/examples
#
# 1) to view interface use:
#       ip a
#    Examples include: eno4 (Dell Servers), ens160 (VMWare), enp0s3, etc.
#    Get  VLAN Tag id
#
# 2) cd /etc/netplan/
# 3) sudo nano 01-netcfg.yaml
#     - NO TABS ALLOWED
# 4) save file
# 5) netplan apply
# 6) ping 1.1.1.1
# 7) ping google.com
#
#
# renderer: "networkd" or "NetworkManager"
#
# DEBUG: sudo netplan --debug apply
# -------------------------------------------------------
network:
  version: 2
  renderer: networkd
  ethernets:
    eno4:
       dhcp4: false
       nameservers:
          addresses: [208.67.222.123,1.1.1.3,9.9.9.9,2606:4700:4700::1113,2620:119:35::123,2620:fe::fe]
  vlans:
      vlan200:
        id: 200
        link: eno4
        addresses:
          - 10.50.1.10/24
        routes:
          - to: default
            via: 10.50.1.1
